language: python
python: 2.7
sudo: true

cache:
  directories:
  - $HOME/chromedriver
  - $HOME/.cache/pip

env:
  - PATH=$PATH:$HOME/chromedriver/ DJANGO_SETTINGS_MODULE=django_project.settings PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

before_install:
  - sudo apt-get install xvfb

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - . ./install_chromedriver.sh

script:
  - cd django_project
  - coverage run --source='.' ./manage.py test --pattern="tests_*.py"

after_success:
  - coveralls